# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Look_At_My_Eyes

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Look_At_My_Eyes

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Look_At_My_Eyes/CMakeFiles /home/pi/Look_At_My_Eyes/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Look_At_My_Eyes/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Look_At_My_Eyes

# Build rule for target.
Look_At_My_Eyes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Look_At_My_Eyes
.PHONY : Look_At_My_Eyes

# fast build rule for target.
Look_At_My_Eyes/fast:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/build
.PHONY : Look_At_My_Eyes/fast

DCMotor.o: DCMotor.cpp.o
.PHONY : DCMotor.o

# target to build an object file
DCMotor.cpp.o:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/DCMotor.cpp.o
.PHONY : DCMotor.cpp.o

DCMotor.i: DCMotor.cpp.i
.PHONY : DCMotor.i

# target to preprocess a source file
DCMotor.cpp.i:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/DCMotor.cpp.i
.PHONY : DCMotor.cpp.i

DCMotor.s: DCMotor.cpp.s
.PHONY : DCMotor.s

# target to generate assembly for a file
DCMotor.cpp.s:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/DCMotor.cpp.s
.PHONY : DCMotor.cpp.s

Image_Process.o: Image_Process.cpp.o
.PHONY : Image_Process.o

# target to build an object file
Image_Process.cpp.o:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/Image_Process.cpp.o
.PHONY : Image_Process.cpp.o

Image_Process.i: Image_Process.cpp.i
.PHONY : Image_Process.i

# target to preprocess a source file
Image_Process.cpp.i:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/Image_Process.cpp.i
.PHONY : Image_Process.cpp.i

Image_Process.s: Image_Process.cpp.s
.PHONY : Image_Process.s

# target to generate assembly for a file
Image_Process.cpp.s:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/Image_Process.cpp.s
.PHONY : Image_Process.cpp.s

findEyeCenter.o: findEyeCenter.cpp.o
.PHONY : findEyeCenter.o

# target to build an object file
findEyeCenter.cpp.o:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/findEyeCenter.cpp.o
.PHONY : findEyeCenter.cpp.o

findEyeCenter.i: findEyeCenter.cpp.i
.PHONY : findEyeCenter.i

# target to preprocess a source file
findEyeCenter.cpp.i:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/findEyeCenter.cpp.i
.PHONY : findEyeCenter.cpp.i

findEyeCenter.s: findEyeCenter.cpp.s
.PHONY : findEyeCenter.s

# target to generate assembly for a file
findEyeCenter.cpp.s:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/findEyeCenter.cpp.s
.PHONY : findEyeCenter.cpp.s

findEyeCorner.o: findEyeCorner.cpp.o
.PHONY : findEyeCorner.o

# target to build an object file
findEyeCorner.cpp.o:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/findEyeCorner.cpp.o
.PHONY : findEyeCorner.cpp.o

findEyeCorner.i: findEyeCorner.cpp.i
.PHONY : findEyeCorner.i

# target to preprocess a source file
findEyeCorner.cpp.i:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/findEyeCorner.cpp.i
.PHONY : findEyeCorner.cpp.i

findEyeCorner.s: findEyeCorner.cpp.s
.PHONY : findEyeCorner.s

# target to generate assembly for a file
findEyeCorner.cpp.s:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/findEyeCorner.cpp.s
.PHONY : findEyeCorner.cpp.s

helpers.o: helpers.cpp.o
.PHONY : helpers.o

# target to build an object file
helpers.cpp.o:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/helpers.cpp.o
.PHONY : helpers.cpp.o

helpers.i: helpers.cpp.i
.PHONY : helpers.i

# target to preprocess a source file
helpers.cpp.i:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/helpers.cpp.i
.PHONY : helpers.cpp.i

helpers.s: helpers.cpp.s
.PHONY : helpers.s

# target to generate assembly for a file
helpers.cpp.s:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/helpers.cpp.s
.PHONY : helpers.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/main.cpp.s
.PHONY : main.cpp.s

sserial.o: sserial.cpp.o
.PHONY : sserial.o

# target to build an object file
sserial.cpp.o:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/sserial.cpp.o
.PHONY : sserial.cpp.o

sserial.i: sserial.cpp.i
.PHONY : sserial.i

# target to preprocess a source file
sserial.cpp.i:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/sserial.cpp.i
.PHONY : sserial.cpp.i

sserial.s: sserial.cpp.s
.PHONY : sserial.s

# target to generate assembly for a file
sserial.cpp.s:
	$(MAKE) -f CMakeFiles/Look_At_My_Eyes.dir/build.make CMakeFiles/Look_At_My_Eyes.dir/sserial.cpp.s
.PHONY : sserial.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Look_At_My_Eyes"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DCMotor.o"
	@echo "... DCMotor.i"
	@echo "... DCMotor.s"
	@echo "... Image_Process.o"
	@echo "... Image_Process.i"
	@echo "... Image_Process.s"
	@echo "... findEyeCenter.o"
	@echo "... findEyeCenter.i"
	@echo "... findEyeCenter.s"
	@echo "... findEyeCorner.o"
	@echo "... findEyeCorner.i"
	@echo "... findEyeCorner.s"
	@echo "... helpers.o"
	@echo "... helpers.i"
	@echo "... helpers.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sserial.o"
	@echo "... sserial.i"
	@echo "... sserial.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

